language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

services:
    - postgresql
addons:
  postgresql: "10.6"

before_script:
    - sudo -u postgres psql -c 'create database test;'

script:
    - pytest
    - coverage run --source=app -m pytest && coverage report

after_success:
    - coveralls
