language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

services:
    - postgresql
addons:
  postgresql: "10.6"

before_script:
    - psql -c 'CREATE DATABASE Questioner;' -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script:
    - pytest
    - coverage run --source=app -m pytest && coverage report

after_success:
    - coveralls
