language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

services:
    - postgresql
postgresql:
    - database: Questioner
    - user: postgres
    - host: localhost
    
before_script:
    - psql -c "CREATE DATABASE Questioner;" -U postgres

script:
    - pytest
    - coverage run --source=app -m pytest && coverage report

after_success:
    - coveralls
