language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

services:
    - postgresql
before_script:
  - psql -c "CREATE DATABASE Questioner;" -U postgres

script:
    - pytest
    - coverage run --source=app -m pytest && coverage report

after_success:
    - coveralls
