language: python
env:
    export FLASK_ENV="testing"
    export DATABASE_URL=postgres://postgres:@localhost:5432/Questioner
    export DATABASE_TEST_URL=postgres://postgres:@localhost:5432/Questioner_Test
    export SECRET_KEY="abraham"
python:
    - "3.6"

install:
    - pip install -r requirements.txt

services:
    - postgresql
before_script:
  - psql -c "CREATE DATABASE Questioner;" -U postgres

script:
    - pytest
    - coverage run --source=app -m pytest && coverage report

after_success:
    - coveralls
