CREATE TABLE IF NOT EXISTS users (u_id SERIAL PRIMARY KEY NOT NULL, firstname VARCHAR (100) NOT NULL, 
lastname VARCHAR (100) NOT NULL, othername VARCHAR (100), username VARCHAR (100) NOT NULL, email VARCHAR (100) NOT NULL, 
phone INTEGER, password VARCHAR (250) NOT NULL, created_at TIMESTAMP);
