/**
 * Questioner API
 * Crowd-source questions for a meetup. Questioner helps the meetup organizer prioritize questions to be answered. Other users can vote on asked questions and they bubble to the top or bottom of the log.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kirumba.kamau@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object GetUserSApi {

  /**
   * Adds an item to the system
   * 
   * Expected answers:
   *   code 200 :  (Successfully fetched)
   *   code 400 :  (bad input parameters)
   */
  def getUsersGet(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://questioner-system.herokuapp.com/api/v2", "/get_users", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * Adds an item to the system
   * 
   * Expected answers:
   *   code 200 :  (Successfully fetched)
   *   code 400 :  (bad input parameters)
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   */
  def profileGet()(implicit apiKey: ApiKeyValue): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://questioner-system.herokuapp.com/api/v2", "/profile", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
      

}

